name: Build check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Baixar Projeto
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Entrar no Projeto
              run: cd civitas-frontend
            
            - name: Instalar Dependências
              run: npm install

            - name: Rodar Build
              run: npm run build